void vector_vector_add(int col, float A[], float B[], float C[]);
void vector_vector_sub(int col, float A[], float B[], float C[]);
void vector_vector_mul(int col, float A[], float B[], float C[]);
void vector_scalar_add(int col, float A[], float num, float C[]);
void vector_scalar_sub(int col, float A[], float num, float C[]);
void vector_scalar_mul(int col, float A[], float num, float C[]);
void matrix_matrix_add(int row, int col, float A[][col], float B[][col], float C[][col]);
void matrix_matrix_sub(int row, int col, float A[][col], float B[][col], float C[][col]);
void matrix_matrix_mul(int row, int col, int len, float A[][len], float B[][col], float C[][col]);
void matrix_scalar_add(int row, int col, float A[][col], float num, float C[][col]);
void matrix_scalar_sub(int row, int col, float A[][col], float num, float C[][col]);
void matrix_scalar_mul(int row, int col, float A[][col], float num, float C[][col]);
void matrix_transpose(int row, int col, float A[][col], float B[][row]);
